apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifact-store
  namespace: apps-build
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: aws-ebs 
  accessModes:
    - ReadWriteOnce