apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: node-build-template
  namespace: apps-build
spec:
  params:
  - name: gitrevision
    description: The git revision
  - name: gitrepositoryurl
    description: The git repository url
  - name: gittag
    description: Contains tag value if need tag has been pushed
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: node-build-run-
    spec:
      serviceAccountName: pipeline-sa
      pipelineRef:
        name: node-build
      params:
      - name: revision
        value: $(tt.params.gitrevision)
      - name: repositoryurl
        value: $(tt.params.gitrepositoryurl)
      - name: tag
        value: $(tt.params.gittag)
      workspaces:
      - name: artifact-store
        persistentVolumeClaim:
          claimName: artifact-store