apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: gitcommit-listener-interceptor
  namespace: apps-build
spec:
  serviceAccountName: tekton-triggers
  resources:
    kubernetesResource:
      serviceType: LoadBalancer
  triggers:
    - name: gitcommit-trigger
      interceptors:
        - github:
            secretRef:
              secretName: github-interceptor-secret
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - ref: gitcommit-trigger-binding
      template:
        ref: node-build-template