apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitcommit-trigger-binding
  namespace: apps-build
spec:
  params:
  - name: gitrevision
    value: $(body.head_commit.id)
  - name: gittag
    value: $(body.ref)
  - name: gitrepositoryurl
    value: $(body.repository.url)
  - name: contenttype
    value: $(header.Content-Type)