apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: app-deploy-template
  namespace: apps-build
spec:
  params:
  - name: gitrevision
    description: The git revision
  - name: gitrepositoryurl
    description: The git repository url
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: app-deploy-run-
    spec:
      serviceAccountName: app-deploy
      pipelineRef:
        name: app-deploy
      params:
      - name: revision
        value: $(tt.params.gitrevision)
      - name: repositoryurl
        value: $(tt.params.gitrepositoryurl)
      workspaces:
      - name: deploy-store
        persistentVolumeClaim:
          claimName: deploy-store